### ISSUE TITLE
Crashing on larger datasets on Windows 10

### ISSUE THREAD

**Issue by smutschall** [martinSergeant/EnteroMSTree#66]
Hello, 
I'm using SA grapetree on Windows 10 using up-to-date chrome and/or firefox. For larger datasets (>10000 strains x 40 loci) I'm getting the "Server returned an error" message. On firefox, I had an additional pop up error from Microsoft Visual C++ Runtime library - something to do with edmonds.exe.  See image below for the message. 

![edmonds exe error](https://user-images.githubusercontent.com/4246723/35286634-c5a801de-001d-11e8-9581-bcee3489f0be.png)

The input file worked using grapetree on ubuntu, generating a tree in a about a minute.

**Comment by zheminzhou** [comment]
You possibly experienced a memory leaking in the windows machine. Could you please specify the amount of the RAM for your windows machine?

**Comment by smutschall** [comment]
I have 16.0 GB RAM and an i7-2600K CPU. 
Thanks!

**Comment by zheminzhou** [comment]
GrapeTree has been redesigned to be more memory friendly. This problem should have been solved. Close temporarily and will re-open it if got new reports.
